function model = train(X, Y, Cval, Sval)
    Sval = .5 / (Sval*Sval);
    model = svmtrain(Y, X, ...
                     sprintf('-q -s 0 -g %f -c %f -w-1 5 -w1 1 -e 1e-7 -h 0', Sval, Cval));

    % Set asymmetric costs for FPs
    %C = ones(size(Y)) .* Cval;
    %C(Y < 0) = 5 .* Cval;
    %
    %model = svmtrain(X, Y, ...
    %                 'kernel_function', 'rbf',  ...
    %                 'rbf_sigma',       Sval,      ...
    %                 'method',          'SMO',  ...
    %                 'autoscale',       false,  ...
    %                 'boxconstraint',   C,      ...
    %                 'options',         statset(...
    %                     'MaxIter', 80000 ...
    %                 )...
    %                );
end